import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./_Components/footer";
import Header from "./_Components/header";
import Provider from "./_Components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="root">
          <Provider>
            <Header />
            {children}
            <Footer />
          </Provider>
        </div>
      </body>
    </html>
  );
}
